# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-51ed9e7e7a364bbcaa1e6b62ae488b54
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-51ed9e7e7a364bbcaa1e6b62ae488b54
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true

# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: picture-1445778052.cos.ap-shanghai.myqcloud.com
    secretId: ${TENCENT_SECRET_ID}
    secretKey: ${TENCENT_SECRET_KEY}
    region: ap-shanghai
    bucket: picture-1445778052

# Pexels 图片搜索配置
pexels:
  api-key: SKf0lozVbOhsE6u9CSJlC5hfaQcQKKlBpHdQ38K0ocrkRIu3oOyFVI1P
